# Generated by Django 2.1.5 on 2019-01-23 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('location_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pensions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pension_img', models.ImageField(blank=True, upload_to='')),
                ('address', models.TextField(blank=True, max_length=100)),
                ('check_in', models.CharField(blank=True, max_length=10)),
                ('check_out', models.CharField(blank=True, max_length=10)),
                ('pick_up', models.TextField(blank=True, max_length=100)),
                ('number_of_room', models.TextField(blank=True, max_length=10)),
                ('notice', models.TextField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_img', models.ImageField(blank=True, upload_to='')),
                ('room_structure', models.TextField(blank=True, max_length=100)),
                ('size', models.TextField(blank=True, max_length=100)),
                ('max_people', models.TextField(blank=True, max_length=100)),
                ('facilities', models.TextField(blank=True, max_length=100)),
                ('room_info', models.TextField(blank=True, max_length=300)),
                ('pension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='location.Pensions')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('sub_location_number', models.CharField(max_length=10)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_location', to='location.Location')),
            ],
        ),
        migrations.AddField(
            model_name='pensions',
            name='sub_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pension', to='location.Sub_location'),
        ),
    ]
