# Generated by Django 2.1.5 on 2019-01-23 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20190122_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_img', models.ImageField(blank=True, upload_to='')),
                ('room_structure', models.TextField(blank=True, max_length=100)),
                ('size', models.TextField(blank=True, max_length=100)),
                ('max_people', models.TextField(blank=True, max_length=100)),
                ('facilities', models.TextField(blank=True, max_length=100)),
                ('room_info', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='pensions',
            name='address',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pensions',
            name='check_in',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='pensions',
            name='check_out',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='pensions',
            name='notice',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pensions',
            name='number_of_room',
            field=models.TextField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='pensions',
            name='pension_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='pensions',
            name='pick_up',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='pension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='location.Pensions'),
        ),
    ]
