# Generated by Django 2.1.5 on 2019-01-24 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20190123_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pensions',
            name='pension_img',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_img',
            field=models.URLField(blank=True),
        ),
    ]
