# Generated by Django 2.1.5 on 2019-01-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20190124_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='pensions',
            name='ypidx',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
