# Generated by Django 2.1.5 on 2019-01-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_pensions_ypidx'),
    ]

    operations = [
        migrations.AddField(
            model_name='pensions',
            name='theme',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
